"""add pricing mode and per size prices

Revision ID: 39fcb02b9096
Revises: d131ec71a3a0
Create Date: 2026-10-01 19:18:05.038640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fcb02b9096'
down_revision: Union[str, Sequence[str], None] = 'd131ec71a3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('price_kobo', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('pricing_mode', sa.String(length=10), server_default='single', nullable=False))
    op.alter_column('products', 'price_kobo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

    # Hand-added (autogenerate does not detect check constraints). Existing rows get
    # pricing_mode 'single' from the column default and already have a price, so they satisfy
    # the new rules. Plain SQL literals are used on purpose: a migration must stay valid forever
    # and so must not import app code that may change.
    op.create_check_constraint(
        "ck_products_pricing_mode_known", "products", "pricing_mode in ('single', 'per_size')"
    )
    op.create_check_constraint(
        "ck_products_price_matches_mode", "products", "(pricing_mode = 'single') = (price_kobo IS NOT NULL)"
    )
    op.create_check_constraint("ck_variants_price_non_negative", "product_variants", "price_kobo >= 0")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_variants_price_non_negative", "product_variants", type_="check")
    op.drop_constraint("ck_products_price_matches_mode", "products", type_="check")
    op.drop_constraint("ck_products_pricing_mode_known", "products", type_="check")
    # Pieces priced per size have no piece price; give them their cheapest size price so the
    # column can be NOT NULL again (the per-size prices themselves are dropped below).
    op.execute(
        "UPDATE products SET price_kobo = (SELECT MIN(price_kobo) FROM product_variants v "
        "WHERE v.product_id = products.id) WHERE price_kobo IS NULL"
    )
    op.alter_column('products', 'price_kobo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'pricing_mode')
    op.drop_column('product_variants', 'price_kobo')
    # ### end Alembic commands ###
