"""create discounts

Revision ID: 5eeeaf6e06b4
Revises: 39fcb02b9096
Create Date: 2026-10-01 19:22:44.404473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eeeaf6e06b4'
down_revision: Union[str, Sequence[str], None] = '39fcb02b9096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('percent_bp', sa.Integer(), nullable=True),
    sa.Column('amount_kobo', sa.Integer(), nullable=True),
    sa.Column('applies_to_all', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'percent' AND percent_bp BETWEEN 1 AND 9999 AND amount_kobo IS NULL) OR (kind = 'amount' AND amount_kobo > 0 AND percent_bp IS NULL)", name='ck_discounts_value_matches_kind'),
    sa.CheckConstraint("kind in ('percent', 'amount')", name='ck_discounts_kind_known'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_discounts_window'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_products',
    sa.Column('discount_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discount_id', 'product_id')
    )
    # ### end Alembic commands ###

    # Hand-added: RLS on with no policies (ADR 0006), for both new tables.
    op.execute("ALTER TABLE discounts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE discount_products ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount_products')
    op.drop_table('discounts')
    # ### end Alembic commands ###
