"""create orders

Revision ID: 6aaf22c0715a
Revises: 7573e4c73895
Create Date: 2026-10-01 20:47:16.596388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaf22c0715a'
down_revision: Union[str, Sequence[str], None] = '7573e4c73895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('subtotal_kobo', sa.Integer(), nullable=False),
    sa.Column('total_kobo', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending', 'paid', 'failed', 'cancelled')", name='ck_orders_status_known'),
    sa.CheckConstraint('subtotal_kobo >= 0', name='ck_orders_subtotal_non_negative'),
    sa.CheckConstraint('total_kobo >= 0', name='ck_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('unit_price_kobo', sa.Integer(), nullable=False),
    sa.Column('base_price_kobo', sa.Integer(), nullable=False),
    sa.Column('discount_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total_kobo', sa.Integer(), nullable=False),
    sa.CheckConstraint('base_price_kobo >= 0', name='ck_order_items_base_price_non_negative'),
    sa.CheckConstraint('line_total_kobo >= 0', name='ck_order_items_line_total_non_negative'),
    sa.CheckConstraint('quantity >= 1', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price_kobo >= 0', name='ck_order_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-added: RLS on with no policies (ADR 0006).
    op.execute("ALTER TABLE orders ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE order_items ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
