"""add cart and per order limit

Revision ID: 7573e4c73895
Revises: 5eeeaf6e06b4
Create Date: 2026-10-01 20:44:09.378136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7573e4c73895'
down_revision: Union[str, Sequence[str], None] = '5eeeaf6e06b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_add_kobo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_at_add_kobo >= 0', name='ck_cart_items_price_non_negative'),
    sa.CheckConstraint('quantity >= 1', name='ck_cart_items_quantity_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'variant_id', name='uq_cart_items_user_variant')
    )
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.add_column('products', sa.Column('max_per_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Hand-added: the owner's per-order limit is optional but, when set, must be at least 1.
    op.create_check_constraint("ck_products_max_per_order_positive", "products", "max_per_order >= 1")
    # Hand-added: RLS on with no policies (ADR 0006).
    op.execute("ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_products_max_per_order_positive", "products", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'max_per_order')
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
