"""add size measurements and fixed size check

Revision ID: d131ec71a3a0
Revises: 5d50eca22c40
Create Date: 2026-10-01 17:21:55.638105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd131ec71a3a0'
down_revision: Union[str, Sequence[str], None] = '5d50eca22c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('measurements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###

    # Hand-added (autogenerate does not detect check constraints). The size list is
    # duplicated here ON PURPOSE: a migration must stay valid forever, so it must not import
    # app code that may change later. Adding a size later means a new migration that replaces
    # this constraint.
    op.create_check_constraint(
        "ck_variants_size_known",
        "product_variants",
        "size in ('XS', 'S', 'M', 'L', 'XL', 'XXL', 'ONE_SIZE')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_variants_size_known", "product_variants", type_="check")
    op.drop_column('product_variants', 'measurements')
    # ### end Alembic commands ###
