"""create auth codes

Revision ID: d930c324ecd2
Revises: 6aaf22c0715a
Create Date: 2026-10-04 23:52:21.960543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd930c324ecd2'
down_revision: Union[str, Sequence[str], None] = '6aaf22c0715a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_challenge', sa.String(length=43), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_auth_codes_user_id'), 'auth_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-added: RLS on with no policies (ADR 0006). The hashed codes are sign-in material.
    op.execute("ALTER TABLE auth_codes ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_codes_user_id'), table_name='auth_codes')
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
